### PR TITLE
redis-stack: revalidateTag shouldn't fetch cache content

### LINKED ISSUE #636: redis-stack: revalidateTag causes OOM crashes due to fetching the full cache content instead of just document ids
redis-stack handler has a problem: When revalidateTag is called, it fetches all cache entries with matching tags using`client.ft.search` method (which uses `FT.SEARCH` command). However since that command fetches the full document by default, if there are enough cache entries that matches the given key to fill the memory, out-of-memory errors happen and the whole nextjs app crashes.

Since the cache contents are not needed, using `client.ft.searchNoContent` would be better. This method uses `FT.SEARCH` with `NOCONTENT` argument and returns document ids (`Array<string>`).

### PR DESCRIPTION
**Pull request by galtonova**
Fetching the whole document causes high memory usage and sometimes causes OOM crashes.
Fixes #636

### CODE REVIEW

File: packages/cache-handler/src/handlers/redis-stack.ts [hunk 1]
```diff
@@ -146,7 +146,7 @@ export default async function createHandler({
             const keysToDelete: string[] = [];
 
             while (true) {
-                const { documents } = await client.ft.search(
+                const documentIds: Array<string> = await client.ft.searchNoContent(
```
Comment (better-salmon) [inline packages/cache-handler/src/handlers/redis-stack.ts]: `searchNoContent` actually returns an object with this shape:

```ts
interface SearchNoContentReply {
    total: number;
    documents: Array<string>;
};
```

Consider using destructuring assignment:

```suggestion
                const { documents } = await client.ft.searchNoContent(
```

File: packages/cache-handler/src/handlers/redis-stack.ts [hunk 2]
```diff
@@ -156,7 +156,7 @@ export default async function createHandler({
                     },
                 );
 
-                for (const { id } of documents) {
+                for (const id of documentIds) {
```
Comment (better-salmon) [inline packages/cache-handler/src/handlers/redis-stack.ts:159]: Please change name here to match the name from above:

```suggestion
                for (const id of documents) {
```

**Review by better-salmon — CHANGES_REQUESTED** [review]
Hello @galtonova! Thank you for contribution! I've just leave suggestions. Could you please address them and then I'll merge your PR.

**Comment by galtonova** [comment]
Hi @better-salmon, it should be OK now.

**Review by better-salmon — APPROVED** [review]
Thank you!

**Comment by better-salmon** [comment]
@galtonova, I've released version 1.4.1 with your fix!
